### ISSUE TITLE
Update Urigen to work with Protege 5.5

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/urigen#8]
Using Urigen in Protege 5.5 created the following failure:

```
2019-05-09 11:13:54.218 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoClassDefFoundError: com/google/common/base/Optional
	at uk.ac.ebi.fgpt.urigen.entity.UrigenEntityFactory.generateName(UrigenEntityFactory.java:53) ~[na:na]
	at org.protege.editor.owl.model.entity.CustomOWLEntityFactory.createOWLEntity(CustomOWLEntityFactory.java:105) ~[na:na]
	at org.protege.editor.owl.ui.OWLEntityCreationPanel.getOWLEntityCreationSet(OWLEntityCreationPanel.java:272) ~[na:na]
	at org.protege.editor.owl.ui.OWLEntityCreationPanel.getOWLEntityCreationSet(OWLEntityCreationPanel.java:253) ~[na:na]
	at org.protege.editor.owl.ui.OWLEntityCreationPanel.showDialog(OWLEntityCreationPanel.java:329) ~[na:na]
	at org.protege.editor.owl.model.OWLWorkspace.createOWLClass(OWLWorkspace.java:957) ~[na:na]
	at org.protege.editor.owl.ui.view.cls.ToldOWLClassHierarchyViewComponent.createNewChild(ToldOWLClassHierarchyViewComponent.java:219) ~[na:na]
	at org.protege.editor.owl.ui.view.cls.ToldOWLClassHierarchyViewComponent$1.actionPerformed(ToldOWLClassHierarchyViewComponent.java:71) ~[na:na]
	at org.protege.editor.core.ui.view.ViewActionAdapter.actionPerformed(ViewActionAdapter.java:48) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) ~[na:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Optional not found by urigen [29]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018) ~[org.apache.felix.main.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
	... 46 common frames omitted
```

**Comment by daniwelter** [comment]
Note that this problem is limited to Protege 5.5 on Mac and does not occur on Linux.

**Comment by zoependlington** [comment]
@paolaroncaglia, @zoependlington, @S2Ola, @twhetzel  to test version 5.5 with URIGen. If it works, then we should all update to 5.5 on the same day.

**Comment by zoependlington** [comment]
All works for me!

**Comment by paolaroncaglia** [comment]
URIGen works for me too for single-entity generation; haven't tried multiple URIs yet.

**Comment by zoependlington** [comment]
Moving to Protege 5.5 on Monday (10th June). Will move to "Done".
